image: microsoft/dotnet:2.1-sdk

stages:
- build
- test
- pack
- nuget

build:
  stage: build
  script:
    - dotnet restore
    - dotnet build --no-restore -c Debug
  artifacts:
    untracked: true
    expire_in: 6 hours

test:
  stage: test
  script:
    - (cd ReflectedCast.Tests; dotnet test -c Debug)
  dependencies:
  - build

pack:
  stage: pack
  script:
    - dotnet pack -c Release --no-restore --include-symbols -o Build
  artifacts:
    untracked: true
    expire_in: 1 week
  dependencies:
  - build

nuget:
  stage: nuget
  script:
    - dotnet nuget push
  dependencies:
  - pack
  only:
  - nuget